FROM castyr/flask_server
MAINTAINER Justin Phillips "justin_phillips@ultimatesoftware.com"
# Create the group and user to be used in this container
RUN pip install -U spacy
RUN pip install -U nltk
RUN python -m spacy download en